function errorNotInRange () {
  throw new RangeError('Please use a Value in range.')
}
export { errorNotInRange }
